# Generated by Django 3.2.7 on 2021-09-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stonks_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('season', models.IntegerField()),
                ('balance_sheet', models.CharField(max_length=5000)),
                ('income_statement', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='DBTest',
        ),
    ]
